spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/healthai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@Coding1@}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=dGhpcylzTXlTdXBlclNlY3JldEtleUZvckpXVEF1dGgxMjM0NTY3ODk=
jwt.expiration=900000

spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=healthai-group
spring.kafka.consumer.auto-offset-reset=earliest
